name: Run Full Experiment with Open Code (v2)

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: "The specific run_id for the full experiment"
        required: true
      experiment_iteration:
        description: "Iteration count"
        required: true
      runner_type:
        description: 'Runner type (e.g., ["ubuntu-latest"], ["self-hosted", "A100"])'
        required: true
        default: '["ubuntu-latest"]'
      model_name:
        description: "Model to use for opencode"
        default: 'anthropic/claude-sonnet-4-5-20250929'

permissions:
  id-token: write
  contents: write
  actions: write

jobs:
  run-experiment:
    name: Run Full Experiment
    runs-on: ${{ fromJSON(github.event.inputs.runner_type) }}
    timeout-minutes: 6000

    outputs:
      experiment_passed: ${{ steps.check-result.outputs.passed }}

    env:
      RESULTS_DIR: ".research/iteration${{ github.event.inputs.experiment_iteration }}"
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.11"

      - name: Prepare results dir
        run: mkdir -p "$RESULTS_DIR"

      - name: Run experiment
        id: run-exp
        continue-on-error: true
        run: |
          trap 'sleep 1' EXIT
          (
            set -e
            set -o pipefail

            echo "=== [UV SYNC] Start at $(date -u) ==="
            uv sync
            echo "=== [UV SYNC] Finished successfully at $(date -u) ==="

            echo "=== [FULL EXPERIMENT] Start for ${{ github.event.inputs.run_id }} at $(date -u) ==="
            uv run python -u -m src.main \
              run=${{ github.event.inputs.run_id }} \
              results_dir="$RESULTS_DIR" \
              mode=full
            echo "=== [FULL EXPERIMENT] PASSED for ${{ github.event.inputs.run_id }} at $(date -u) ==="
          ) > >(tee -a "$RESULTS_DIR/stdout.txt") 2> >(tee -a "$RESULTS_DIR/stderr.txt" >&2)

      - name: Check result
        id: check-result
        run: |
          if [[ "${{ steps.run-exp.outcome }}" == "success" ]] && grep -q "\[FULL EXPERIMENT\] PASSED" "$RESULTS_DIR/stdout.txt"; then
            echo "✅ Experiment passed"
            echo "passed=true" >> "$GITHUB_OUTPUT"
          else
            echo "❌ Experiment failed"
            echo "passed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: experiment-results-${{ github.run.id }}
          path: ${{ env.RESULTS_DIR }}


  fix-and-rerun:
    name: Fix and Re-run
    runs-on: ubuntu-latest
    needs: run-experiment
    if: needs.run-experiment.outputs.experiment_passed == 'false'
    timeout-minutes: 60

    env: 
      RESULTS_DIR: ".research/iteration${{ github.event.inputs.experiment_iteration }}"
      SEARCH_HF_COMMAND: |
        curl -s -G \
          -H "Authorization: Bearer $HF_TOKEN" \
          --data-urlencode "search=${SEARCH_TERM}" \
          --data-urlencode "sort=likes" \
          --data-urlencode "limit=10" \
          --data-urlencode "direction=-1" \
          --data-urlencode "full=true" \
          "https://huggingface.co/api/${RESOURCE_TYPE}" \
        | jq -r '(.results // .) | map(select(.gated == false and .private == false and .disabled == false)) | .[0]?.id // empty'
      PROMPT: |
        Your task is to correct the code for the experiment associated with run ID ${{ github.event.inputs.run_id }}.
        You have been granted full tool access. 

        Your operational environment is a standard CPU-only runner without GPUs. 
        Any attempt to run the experiment code will fail and lead to incorrect conclusions. Your sole responsibility is to **modify the code to make it runnable**. 
        The actual experiment will be executed in a separate, GPU-enabled environment after your corrections.

        ERROR INFORMATION:
        The error logs are available in the file: $RESULTS_DIR/error_summary.txt
        Read this file to understand what went wrong. DO NOT read stdout.txt or stderr.txt as they contain verbose training logs.

        Guiding Principles:
        - Scope: Do not perform any Git operations like commit or push. Your only task is to fix the code to make it executable.
        - Method: When fixing errors, you MUST only modify existing files; do not create or delete any files.
        - Autonomy: Perform all correction steps autonomously. Do not ask for permission.
        - Resource Errors: If a Hugging Face resource is unavailable, you MUST find and implement a public alternative. To do this, you MUST first set two variables:
          1.  `RESOURCE_TYPE`: Set to either `"models"` or `"datasets"`.
          2.  `SEARCH_TERM`: Set to the resource name from the error to find a corrected or alternative ID.
          Then, execute `bash -c "$SEARCH_HF_COMMAND"` to get the best alternative ID and update the code.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download experiment results
        uses: actions/download-artifact@v4
        with:
          name: experiment-results-${{ github.run.id }}
          path: ${{ env.RESULTS_DIR }}

      - name: Extract error summary
        run: |
          if [ -f "$RESULTS_DIR/stderr.txt" ]; then
            echo "=== ERROR SUMMARY (Last 100 lines of stderr) ===" > "$RESULTS_DIR/error_summary.txt"
            tail -n 100 "$RESULTS_DIR/stderr.txt" >> "$RESULTS_DIR/error_summary.txt"
          fi

          if [ -f "$RESULTS_DIR/stdout.txt" ]; then
            echo -e "\n=== RELEVANT STDOUT (Error/Exception lines) ===" >> "$RESULTS_DIR/error_summary.txt"
            grep -i -E "(error|exception|traceback|failed|fatal)" "$RESULTS_DIR/stdout.txt" | tail -n 50 >> "$RESULTS_DIR/error_summary.txt" || echo "No error patterns found in stdout" >> "$RESULTS_DIR/error_summary.txt"
          fi
          
          cat "$RESULTS_DIR/error_summary.txt"

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install bun
        run: npm install -g bun

      - name: Install opencode
        run: |
          curl -fsSL https://opencode.ai/install | bash

      - name: Run OpenCode Fix
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        run: |
          for i in {1..10}; do
            opencode run --model "${{ github.event.inputs.model_name }}" "$PROMPT" && break
            if [ $i -lt 10 ]; then
              echo "Attempt $i failed with exit code $?. Retrying in $((2**i)) seconds..."
              sleep $((2**i))
            else
              echo "All 10 attempts failed."
              exit 1
            fi
          done

      - name: Commit and push fix
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git add --update .

          if ! git diff --staged --quiet; then
            git commit -m "[CI] Automated fix for run_id=${{ github.event.inputs.run_id }}"
            for i in {1..5}; do
              git pull --rebase && git push && break
              echo "Push failed on attempt $i. Retrying in $((2**i)) seconds..."
              sleep $((2**i))
            done
          else
            echo "OpenCode made no changes to the code."
          fi

      - name: Trigger next iteration
        run: |
          echo "Re-running workflow"
          gh workflow run "${{ github.workflow }}" --ref ${{ github.ref }} \
            -f run_id="${{ github.event.inputs.run_id }}" \
            -f experiment_iteration="${{ github.event.inputs.experiment_iteration }}" \
            -f runner_type='${{ github.event.inputs.runner_type }}' \
            -f model_name='${{ github.event.inputs.model_name }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  commit-successful-results:
      name: Commit Successful Results
      runs-on: ubuntu-latest
      needs: run-experiment
      if: needs.run-experiment.outputs.experiment_passed == 'true'

      env:
        RESULTS_DIR: ".research/iteration${{ github.event.inputs.experiment_iteration }}"

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Download successful results
          uses: actions/download-artifact@v4
          with:
            name: experiment-results-${{ github.run.id }}
            path: ${{ env.RESULTS_DIR }}


        - name: Commit and push experiment results
          run: |
            git config --local user.name "github-actions[bot]"
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
            git add .research/
            
            if ! git diff --staged --quiet; then
              git commit -m "[CI] Commit all changes from autonomous run (iteration ${{ github.event.inputs.experiment_iteration }})"
              for i in {1..5}; do
                git pull --rebase && git push && break
                echo "Push failed on attempt $i. Retrying in $((2**i)) seconds..."
                sleep $((2**i))
              done
            else
              echo "No changes were made by the agent or the experiment."
            fi

